ably/ably-chat-js

.github/workflows/release.yml

[CHA-220]
- Fixes NPM publish
Can't test until landed in main.

release: fix npm publish

---

scripts/cdn_deploy.js

[CHA-220]
use the correct include dir for the CDN upload
N/A.

release: fix CDN include dirs

---

COPYRIGHT

Adds the COPYRIGHT file to the repository root, per the engineering standards.
[CHA-220]
Adds the COPYRIGHT file to the repository root, per the engineering standards.
N/A

docs: add copyright file to repo root

---

MAINTAINERS.md

[CHA-220]
This change adds a `MAINTAINERS.md` file to the repo, inline with engineering standards.
N/A

docs: add maintainers file to repo root

---

.github/workflows/dev.yml

[CHA-220]
Adds a step to the test workflow that also writes a comment to the PR summarising the test coverage, if the PR has come from an Ablyan.
See the comment below this on the PR!

build: publish code coverage report as PR comment (POC)

---

README.md

Updates the README with:
- Compatibility information
- CDN links
- NPM Shield
- General corrections

docs: add contribution, support links and fix copy

---

vitest.config.ts

[CHA-220]
Ignores entrypoint and empty lines from code coverage calculations, so they're more accurate.
N/A

test: ignore entrypoint and empty lines from coverage calculation

---

demo/src/containers/Chat/Chat.tsx

* [CHA-339]
* Part of continuous improvements to the demo app.
* Added auto scroll to the demo app messages component, this will keep the latest message in view as new messages are received.
* Spin up the demo app, send messages until messages component is full. 
* New messages should now cause the component to autoscroll and keep the latest message in view.
[CHA-339]: https://ably.atlassian.net/browse/CHA-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

demo-app: add auto-scroll to chat box

---

.github/PULL_REQUEST_TEMPLATE.md

Added a section to the definition of done for making changes to react hooks.

template: updated PR template for react hooks.

---

test/core/presence.integration.test.ts
test/core/typing.integration.test.ts

[CHA-404]
- Fixes a flakey test in typing, that was flaking due to the fact we conflate the typing updates where necessary.
- Adds extra logging to a presence test that flakes, so it can be more easily be debugged.
N/A
[CHA-404]: https://ably.atlassian.net/browse/CHA-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Flakey tests

---

src/react/hooks/use-occupancy.ts
test/react/hooks/use-occupancy.integration.test.tsx

- CHA-389
- Fixes a flakey test in relation to occupancy
- Removes a console log

react: fix useOccupancy flakey test

---

src/react/README.md

[CHA-382]
- Adds README entries for `useRoom` and `ChatRoomProvider`
N/A

docs: add useRoom and ChatRoomProvider to React README

---

src/react/contexts/chat-client-context.tsx
src/react/contexts/chat-room-context.tsx
src/react/hooks/use-chat-client.ts
src/react/hooks/use-chat-connection.ts
src/react/hooks/use-logger.ts
src/react/hooks/use-messages.ts
src/react/hooks/use-occupancy.ts
src/react/hooks/use-presence-listener.ts
src/react/hooks/use-presence.ts
src/react/hooks/use-room-reactions.ts
src/react/hooks/use-room.ts
src/react/hooks/use-typing.ts
src/react/providers/chat-client-provider.tsx
src/react/providers/chat-room-provider.tsx

* [CHA-392]
* Updated typedocs comments throughout the chat react hooks library.
[CHA-392]: https://ably.atlassian.net/browse/CHA-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

react-hooks: Clean up the typedocs in the Chat react library

---

src/react/hooks/use-messages.ts

[CHA-384]
When running React in strict mode, its possible to call getPreviousMessages between the subscription being removed and the setState taking effect. This causes an error to be thrown as getPreviousMessages requires the subscription to work.
To resolve this, we check if the hook has unmounted before calling getPreviousMessages and return a dummy value if it has.
- Run demo app, observe the lack of errors.
[CHA-384]: https://ably.atlassian.net/browse/CHA-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix/react: dont do getPreviousMessages if hook ummounts

---

test/core/chat.integration.test.ts
test/core/occupancy.integration.test.ts
test/react/hooks/use-occupancy.integration.test.tsx

[CHA-580]
This change fixes the occupancy tests to account for recent changes in Realtime that affect the numbers.
Run tests!
[CHA-580]: https://ably.atlassian.net/browse/CHA-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: fix occupancy tests

---

src/core/events.ts

Correcting wrong annotation type.

fix: Correct annotation enum

---

README.md

the package currently doesn't have a default export

docs: fix `ChatClient` import statement

---

test/core/messages.integration.test.ts

Removes a debug log I accidentally left in.
N/A

test: remove debug log

---

demo/package-lock.json
demo/package.json

This change bumps ably-js in the demo app temporarily to enjoy the field changes whilst the ably-js changes are released.
Run the demo app against sandbox - everything should work.

demo: bump ably-js version to branch

---

README.md

Recent link for viewing defaults options on each feature.

docs(README): intended link room-options

---

src/react/README.md

Type should be an array of messages in the docs.

Docs: Fixed a small typing issue in the react docs for updates.

---

README.md

Adds edit/delete to the features list in the README.

docs: add edit delete to features list

---

test/react/hooks/use-presence.integration.test.tsx

* [CHA-782]
* We found a race condition caused by umounting the component in the `usePresence` test. During unmount, we attempt to `leave` presence. Due to how the test is written, unmounting also detaches us from the channel. In the race between the former and the latter, the latter wins and so the `leave` call fails since we are no longer in an `attached` state.
* Update the test so the Providers do not umount, this means we can test the hooks unmount process without triggering the detach.
[CHA-782]: https://ably.atlassian.net/browse/CHA-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bugfix: Fix race condition in usePresence test

---

demo/package-lock.json
demo/package.json
package-lock.json
package.json
test/core/helpers.test.ts
test/react/hooks/use-presence.integration.test.tsx

upgrading ably dependencies to version 2.6.1 to fix broken tests

Chore: Upgrade Ably dependency to version 2.6.2

---

README.md

[CHA-777]
This change removes mentions of "beta" from the README.
From now, we will mark "experimental" features as such - but the overall repo stability shall be dictated by its SemVer version.
N/A
[CHA-777]: https://ably.atlassian.net/browse/CHA-777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: remove reference to beta

---

CHANGELOG.md
CONTRIBUTING.md
UPGRADING.md
demo/README.md
demo/package-lock.json
package-lock.json
package.json
src/core/version.ts
typedoc.json

N/A
This PR contains the documentation and version updates to facilitate the release of version 0.4.
N/A

chore: 0.4.0 release

---

demo/README.md

Formatting Alert Markdown for Note section
Include relative links running local

style(demo): local realtime links

---

demo/src/App.tsx
src/core/index.ts
src/core/room-options.ts
src/react/providers/chat-room-provider.tsx
test/core/messages.integration.test.ts
test/core/presence.integration.test.ts
test/core/room.test.ts
test/core/rooms.integration.test.ts
test/core/typing.integration.test.ts
test/helper/room.ts
test/react/helper/use-eventual-room.test.tsx
test/react/helper/use-room-context.test.tsx
test/react/helper/use-room-status.test.tsx
test/react/hooks/use-messages.integration.test.tsx
test/react/hooks/use-occupancy.integration.test.tsx
test/react/hooks/use-presence-listener.integration.test.tsx
test/react/hooks/use-presence.integration.test.tsx
test/react/hooks/use-room-reactions.integration.test.tsx
test/react/hooks/use-room.test.tsx
test/react/hooks/use-typing.integration.test.tsx
test/react/providers/chat-room-provider.integration.test.tsx
test/react/providers/room-provider.test.tsx

Docs PR https://github.com/ably/docs/pull/2418

Rename RoomOptionsDefault -> DefaultRoomOptions

---

README.md
cspell.json

[CHA-817]
This change includes a "getting started" guide, aimed at guiding developers to sending their first message using Ably Chat. This will be replicated on the website and dashboard.
Please try these examples yourself and check that they work!
[CHA-817]: https://ably.atlassian.net/browse/CHA-817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: getting started guide

---

CHANGELOG.md
UPGRADING.md
demo/package-lock.json
package-lock.json
package.json
src/core/version.ts

This PR performs the necessary actions for the 0.5.0 release.

release: prepare docs for 0.5.0 release

---

CHANGELOG.md
demo/package-lock.json
package-lock.json
package.json
src/core/version.ts

Changelog and version updates for the 0.5.1 release.
N/A.

release: prepare v0.5.1 release

---

.github/workflows/docs.yml
README.md

N/A
This PR updates readme to provide correct example of imports of ChatClientProvider and ChatRoomProvider for react.
N/A

Fix React imports in the example in the Readme

---

src/core/room-options.ts
test/core/messages-reactions.integration.test.ts
test/core/messages-reactions.test.ts
test/core/presence.test.ts
test/core/room-options.test.ts
test/core/room.test.ts

https://ably.atlassian.net/browse/CHA-982

Disable raw reactions by default

---

.github/workflows/deps-updated-correctly.yml
.github/workflows/dev.yml

N/A
Include Node 24 (next LTS) in our testing.
N/A

dev: test against node 24

---

CHANGELOG.md
UPGRADING.md
demo/package-lock.json
package-lock.json
package.json
src/core/version.ts

[CHA-955]
Updates the version number and documentation for the 0.8.0 release.
[CHA-955]: https://ably.atlassian.net/browse/CHA-955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

release: 0.8.0

---

.cursor/rules/general.mdc
.cursor/rules/integration-testing.mdc
.cursor/rules/unit-testing.mdc
.github/workflows/dev.yml
package.json
src/core/channel-manager.ts
src/core/chat-api.ts
src/core/rest-types.ts
src/core/room-status.ts
src/core/typing.ts
src/core/version.ts
src/react/providers/chat-room-provider.tsx
test/core/channel-manager.test.ts
test/core/chat.integration.test.ts
test/core/realtime.test.ts
test/core/rest-types.test.ts
test/core/typing.test.ts
test/helper/room.ts
test/react/helper/use-eventual-room.test.tsx
test/react/hooks/use-messages.test.tsx
test/react/hooks/use-presence-listener.test.tsx
test/react/providers/chat-room-provider.test.tsx
vitest.config.ts

* Turn off test coverage by default, as it slows things down quite a bit.
* Add test with coverage npm command
* Adds a number of tests in uncovered areas
N/A

test coverage

---

src/core/chat-api.ts
src/core/message-parser.ts
src/core/messages.ts
src/core/rest-types.ts
test/core/message-parser.test.ts
test/core/messages.integration.test.ts
test/core/messages.test.ts
test/core/rest-types.test.ts

[CHA-1040]
Fix #578 
This pull request refactors the `parseMessage` function in `src/core/message-parser.ts` to improve its handling of deleted messages and enforces stricter validation for incoming message payloads. It also updates the corresponding test cases to reflect these changes.
* Refactored `parseMessage` to use an arrow function.
* Enhanced validation for incoming messages:
- Added checks to ensure `extras`, `extras.headers`, and `data.metadata` are present for non-delete messages.
- Simplified handling of deleted messages by setting `data` and `extras` to empty objects.
Functionally for users, it means that deleted messages will have no text, metadata or headers.
* Updated test cases in `test/core/message-parser.test.ts`:
- Adjusted test data to include `extras.headers` and …

Deleted messages blank data

---

CONTRIBUTING.md

- Adds CONTRIBUTING.md step to include updating `@ably/cli`

docs: add @ably/cli step to release process

---

CHANGELOG.md
CONTRIBUTING.md
UPGRADING.md
demo/package-lock.json
package-lock.json
package.json
src/core/version.ts

Contains the necessary changes for 0.10.0 release.

chore: prepare 0.10.0 release
