scripts/cdn_deploy.js
[CHA-220]
- Fix the CDN deploy script to run when the repo is a module.
Run `node scripts/cdn_deploy.js --skipCheckout --tag=0.1.0` - it won't work locally but it at least won't error because of imports.
=> release: fix cdn deploy script

.eslintrc.cjs, demo/package-lock.json, package-lock.json, package.json
[CHA-396]
Adds the eslint-plugin-compat plugin to our eslint config that checks browser conformance.
The settings are for all "modern" browsers, except opera mini, as that doesn't support promises.
To prove plugin is doing as intended - remove the "not op_mini all" from package.json and run lint, it should fail.
[CHA-396]: https://ably.atlassian.net/browse/CHA-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> dev: add eslint plugin for browser compatibility

demo/src/App.tsx, demo/src/components/UserPresenceComponent/UserPresenceComponent.css, demo/src/components/UserPresenceComponent/UserPresenceComponent.tsx, demo/src/components/UserPresenceComponent/index.ts, demo/src/hooks/usePresence.ts, demo/styles/global.css
* [CHA-343]
* The demo app did not use the presence capability of the chat SDK, so this PR adds some basic usage.
* Added UserPresenceComponent and presence hook used to interactive with the presence feature
* Component displays the list of present clientIds and their associated status
* Component also allows the user to enter presence, update their status to `away`, and leave presence.
* Added some global and component styling.
* Spin up the demo app, try pressing the buttons and check the presence list updates.
[CHA-343]: https://ably.atlassian.net/browse/CHA-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> demo-app: added presence capability

README.md, src/core/helpers.ts, src/core/index.ts, src/core/message-parser.ts, src/core/messages.ts, src/core/reaction-parser.ts, src/core/room-reactions.ts, test/core/helpers.test.ts, test/core/message-parser.test.ts, test/core/reaction-parser.test.ts
* [CHA-337]
* Users may wish to make use of ably's integration offerings, such as webhooks/AWS lambdas, where messages/reactions etc. sent to the room can be filtered and sent to an integration. It would be useful to have some functions set up that users can pass an encoded inbound message-like object and decode them straight into a chat type like a message or reaction.
- Added two functions that take an encoded ably message, such as those sent via integration rules, and try to convert them into chat types. 
- Added fromEncodedChatMessage function that will try and convert the message into a chat message. 
- Added fromEncodedReaction function that will try and convert the message into a reaction.
- Added getEntityTypeFromEncoded function that will also take an encoded message, and attempt …
=> feature: Added Public Ably Message Parsers 

demo/src/App.tsx, demo/src/components/MessageInput/MessageInput.tsx, demo/src/components/ReactionInput/ReactionInput.tsx, demo/src/containers/Chat/Chat.tsx, demo/src/hooks/useMessages.ts, demo/src/hooks/usePresence.ts, demo/src/hooks/useReactions.ts, demo/src/hooks/useRoom.ts, demo/src/hooks/useTypingIndicators.ts, demo/src/main.tsx
Add and cleanup comments in the demo app and some refactoring where it made sense to simplify things.
https://ably.atlassian.net/browse/CHA-342
Added, removed and fixed comments in different places across the app.
Removed unused things, like a `const mounted = true` and stopped returning `clientId` in `useReactions`.
Simplified the way we read and reset the `value` of `MessageInput`.
Refactored the typing indicators hook to work similar to how the messages hook works. It now includes a fetch on mount so that the current state of typing indicators is shown in the case if someone started typing before you entered the room.
- Read the code with comments
- Let me know if I should add more comments or change wording, do more or less in different parts, add links, etc
- Optional: run the demo …
=> Demo: add comments and small refactoring

__mocks__/ably/index.ts, demo/package-lock.json, demo/src/App.tsx, demo/src/components/UserPresenceComponent/UserPresenceComponent.tsx, demo/src/containers/RoomContext/RoomProvider.tsx, demo/src/main.tsx, package-lock.json, src/core/chat.ts, src/react/README.md, src/react/contexts/chat-client-context.tsx, src/react/hooks/use-chat-client.ts, src/react/index.ts, src/react/providers/chat-client-provider.tsx, src/react/tsconfig.json, test/core/chat.integration.test.ts, test/react/hooks/use-chat-client.test.tsx, test/react/providers/chat-client-provider.test.tsx, typedoc.json
* Provide name of JIRA ticket that this PR is related to (if applicable).
* e.g. [CHA-101] - this will automatically link the PR to the JIRA ticket.
* Provide names of any related DRs (if applicable).
* Provide links to any related PRs
* Added `useChatClient` custom hook that allows the user to retrieve the current chat client from the nearest context.
* Added `ChatClientContext` and `ChatClientProvider`, which are necessary for using the new hook.
* These components ensure that there is only a single instance of the chat context at any given level in the component tree. 
* Updated tsconfig to recognise the new context and provider files.
* Start the demo app, check you can send reaction, messages and enter presence.
[CHA-101]: https://ably.atlassian.net/browse/CHA-101?atlOrigin=eyJpIjoiNW …
=> react-hooks: add useChatClient hook, related context and provider

src/react/tsconfig.json, tsconfig.json
We need to specify the extensions separately as globs don't do regular expressions. This change ensures that we specify paths properly so that ESLint picks them up.
N/A
=> dev: fix tsconfig paths

src/react/chat-status-response.ts, src/react/index.ts, src/react/listenable.ts, src/react/status-params.ts, vitest.config.ts
Adds interfaces as they are defined in CHADR-030. Closes [CHA-383]. They will be used for future hooks.
n/a
[CHA-383]: https://ably.atlassian.net/browse/CHA-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> react hooks: add base interfaces Listenable, StatusParmas and ChatStatusResponse

demo/package-lock.json, demo/src/components/ConnectionStatusComponent/ConnectionStatusComponent.tsx, demo/src/components/ConnectionStatusComponent/index.ts, demo/src/components/MessageInput/MessageInput.tsx, demo/src/components/OccupancyComponent/OccupancyComponent.tsx, demo/src/components/ReactionInput/ReactionInput.tsx, demo/src/components/UserPresenceComponent/UserPresenceComponent.tsx, demo/src/containers/Chat/Chat.tsx, src/core/index.ts, src/react/README.md, src/react/hooks/use-chat-connection.ts, src/react/index.ts, test/react/hooks/use-chat-connection.test.tsx
* [CHA-381]
* Introduced useChatConnection to allow users to subscribe to connection status changes.
* A listener can also be supplied to the hook if the user wants the underlying status changes.
* Added some basic usage to the demo app.
[CHA-381]: https://ably.atlassian.net/browse/CHA-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> react-hooks: add useChatConnection hook

src/react/chat-status-response.ts
* Currently, the `ChatStatusReponse` exposes the room status and connection status objects. This isn't really needed by the other react hooks, the current state and error is sufficient. 
* Updated the `ChatStatusReponse` interface so it now returns the `ConnectionLifecycle` and `RoomLifecycle` types in place of their respective status objects.
=> react-hooks: Update ChatStatusResponse attributes

src/core/chat-api.ts, test/core/chat-api.test.ts
- Updates ChatApi to pass the correct protocol version to `realtime.request`
- The value should be an integer, the current value in ably-js being 3.
- This won't have any significant effect on what we're calling, as we version our API for chat by endpoint, but it ensures that our request is nonetheless valid.
N/A
=> api: pass correct api protocol version to realtime.request

src/core/room-options.ts
This allows `RoomOptionsDefaults` to be used directly in `rooms.get("abc", RoomOptionsDefaults)`. The class version made `dequal` throw an error if you did the above on the same room twice.
=> export RoomOptionsDefaults as a struct instead of a class

src/core/messages.ts
(I couldn't see any documentation that explained this.)
=> Document the order of messages returned by `getPreviousMessages`

cspell.json, demo/src/components/MessageInput/MessageInput.tsx, package.json, src/core/discontinuity.ts, src/core/index.ts, src/core/messages.ts, src/core/occupancy.ts, src/core/presence.ts, src/core/room-lifecycle-manager.ts, src/core/room-reactions.ts, src/core/room-status.ts, src/core/room.ts, src/core/rooms.ts, src/core/typing.ts, test/core/messages.integration.test.ts, test/core/messages.test.ts, test/core/occupancy.integration.test.ts, test/core/occupancy.test.ts, test/core/presence.integration.test.ts, test/core/room-lifecycle-manager.test.ts, test/core/room-reactions.integration.test.ts, test/core/room-reactions.test.ts, test/core/room-status.test.ts, test/core/room.integration.test.ts, test/core/room.test.ts, test/core/rooms.integration.test.ts, test/core/rooms.test.ts, test/core/typing.integration.test.ts, test/core/typing.test.ts, test/helper/room.ts
The problem is also described at [CHADR-049] and (loosely) tracked at [CHA-382](https://ably.atlassian.net/browse/CHA-382).
Our current public API allows users to get a room that is currently being released, which is undesirable:
```typescript
// options emitted for brevity
const r1 = rooms.get("abc");
rooms.release("abc").then(() => { console.log("released abc"); });
const r2 = rooms.get("abc"); // this is the room being released, unusable right now but we want it to work
// -> released abc
const r3 = rooms.get("abc") // this is now usable
```
The changes in this PR make `r2` above to be a usable room, which will have status `initializing` until the previous room (from `r1`) finishes releasing. No realtime channels are created in `initializing` state. Realtime channels are created when …
=> Async room initialisation

README.md, src/core/vite.config.ts, src/react/vite.config.ts
We were having some issues with using ably-js and ably-chat-js from the CDN, as the former doesn't export an ESM module (and the later tries to import it).
- Update the Vite library names for Chat and React to be `AblyChat` and `AblyChatReact` respectively. This means that users can do `const chatClient = new AblyChat.ChatClient()` instead of `const chatClient = new window['ably-chat-js'].ChatClient()` in the browser.
- Update the README instructions for using the CDN to point to the UMD variant of Chat, which does work with ably-js.
- Update the React dependencies to make `react-dom` and `react/jsx-runtime` externals - requiring the consumer to provide them and avoiding conflicts.
Minimal working example:
```html
<script src="https://cdn.ably.com/lib/ably.min-2.js"></script>
<script …
```
=> CDN Bundle Fixes

demo/src/components/UserPresenceComponent/UserPresenceComponent.tsx, src/react/README.md, src/react/hooks/use-presence-listener.ts, src/react/index.ts, test/react/hooks/use-presence-listener.integration.test.tsx, test/react/hooks/use-presence-listener.test.tsx, test/react/hooks/use-presence.integration.test.tsx, test/react/hooks/use-room-reactions.integration.test.tsx, test/react/hooks/use-typing.integration.test.tsx
* [CHA-388]
- Added the `usePresenceListener` hook to the Chat React library. This allows the user to interact with the underlying `Presence` instance, and subscribe a listener to presence events.
- The hook also returns the current state of presence members, which is kept up to date by the hook.
- Updated the demo app to use the new hook, the presence list is now updated via the returned state from the hook.
- Updated the readme to document hook usage.
- Added unit tests for the new hook.
- Added integration tests for the new hook.
1. Spin up a local instance of the demo app.
2. Open up two tabs with different clients and join presence
3. Ensure both tabs show presence for both clients
[CHA-388]: https://ably.atlassian.net/browse/CHA-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
=> react-hooks: Add usePresence listener hook

src/core/chat.ts, src/core/index.ts, src/react/hooks/use-chat-connection.ts, src/react/hooks/use-logger.ts, src/react/hooks/use-occupancy.ts, src/react/hooks/use-presence-listener.ts, src/react/hooks/use-presence.ts, src/react/hooks/use-room-reactions.ts, src/react/hooks/use-room.ts, src/react/hooks/use-typing.ts, src/react/providers/chat-room-provider.tsx, test/react/hooks/use-chat-connection.test.tsx, test/react/hooks/use-occupancy.test.tsx, test/react/hooks/use-presence-listener.test.tsx, test/react/hooks/use-presence.test.tsx, test/react/hooks/use-room-reactions.test.tsx, test/react/hooks/use-room.test.tsx, test/react/hooks/use-typing.test.tsx
N/A
This change introduces a new hook `useLogger`, which is intended to be an internal hook. The purpose of the hook is to expose the logger on the `ChatClient`, which allows us to use the logger to log events in the React hooks, including errors, traces and more.
To achieve this, we add `logger` as an internal property on the `ChatClient`, so that the hook can get it.
This change also adds logging across the hooks that exist so far.
Turn on trace logging and see that logs happen!
=> Use logger hook

src/react/README.md, src/react/helper/use-event-listener-ref.ts, src/react/hooks/use-chat-connection.ts, src/react/hooks/use-messages.ts, src/react/hooks/use-occupancy.ts, src/react/hooks/use-presence-listener.ts, src/react/hooks/use-presence.ts, src/react/hooks/use-room-reactions.ts, src/react/hooks/use-room.ts, src/react/hooks/use-typing.ts, src/react/types/status-params.ts, test/react/helper/use-event-listener-ref.test.tsx, test/react/hooks/use-messages.integration.test.tsx, test/react/hooks/use-messages.test.tsx, test/react/hooks/use-occupancy.test.tsx, test/react/hooks/use-presence-listener.test.tsx, test/react/hooks/use-presence.test.tsx, test/react/hooks/use-room-reactions.test.tsx, test/react/hooks/use-room.test.tsx, test/react/hooks/use-typing.test.tsx
N/A
A number of our hooks allow users to pass in their own listeners to be able to monitor events such as new messages or occupancy updates, even if the hook exposes the latest data.
At present, we use the listener param in a useEffect to apply listener subscriptions. This causes listener cycling if the hook is called using an inline listener, as the reference changes every time. This behaviour is not desired, as it may cause the subscriber to miss events.
This change fixes the issue by introducing a new internal hook, useEventListenerRef. This hook creates a stable reference to the passed in listener between re-renders. So whilst the underlying listener may change, we avoid cycling subscriptions on every render and thus potentially missing messages.
We also replace all instances of …
=> react: use stable references to event listeners in hooks

test/react/hooks/use-chat-client.test.tsx, test/react/hooks/use-chat-connection.test.tsx, test/react/hooks/use-messages.integration.test.tsx, test/react/hooks/use-messages.test.tsx, test/react/hooks/use-occupancy.integration.test.tsx, test/react/hooks/use-occupancy.test.tsx, test/react/hooks/use-presence-listener.integration.test.tsx, test/react/hooks/use-presence-listener.test.tsx, test/react/hooks/use-presence.integration.test.tsx, test/react/hooks/use-presence.test.tsx, test/react/hooks/use-room-reactions.integration.test.tsx, test/react/hooks/use-room-reactions.test.tsx, test/react/hooks/use-room.test.tsx, test/react/hooks/use-typing.integration.test.tsx, test/react/hooks/use-typing.test.tsx, test/react/providers/chat-client-provider.test.tsx, test/react/providers/room-provider.test.tsx
* Some of the tests were experiencing flaky failures, I believe this was in part due to not unmounting hooks correctly after each test. 
* It seems we also dumped expected throw error information to the console log, this was unnecessary and could be removed.
* A package that is no longer used had been left in the package-lock file.
* Removed the unused lodash package.
* Refactored the test case for `useChatClient` to use a dedicated `TestThrowError` component for throwing errors outside of `ChatClientProvider`. (`test/react/hooks/use-chat-client.test.tsx`)
* Added `cleanup` calls to ensure proper unmounting of components after each test case.
=> react-hooks: Cleanup and fix hook tests.

demo/src/containers/Chat/Chat.tsx
The demo app shows typing indicator for the current user (yourself). This PR filters your own typing indicators out before displaying them.
- Open two tabs.
- _Tip: change clientIds on both to something human-readable_
- Type something. You should now only see the other tab's typing indicator, not your own.
=> demo: stop showing typing indicator for current user

src/react/hooks/use-typing.ts, test/react/hooks/use-typing.test.tsx
I've noticed that this error was shown briefly when loading the demo app and started digging:
This only happens when you are still waiting for something from a room that's been released, which means we update an old state. The room is only released when a parent component of what we see there (ChatRoomProvider) is unmounted.
The existing version of this code was also not setting the unsubscribe from the hook correctly.
This version uses a simple `mounted` variable to address the problem. Commits in a [previous PR #342] (https://github.com/ably/ably-chat-js/pull/342) attempted 2 different approaches but both turned out be more trouble than worth.
Open demo app - enjoy the absence of the flashing error.
=> react: ensure we don't show old errors in typing indicators

.eslintrc.cjs, README.md, cspell.json, demo/package-lock.json, package-lock.json, package.json, src/core/room.ts
[CHA-494]
This method is not available in React Native runtimes, so replace it with the `lodash.cloneDeep` function instead, which is entirely self-contained.
N/A
[CHA-494]: https://ably.atlassian.net/browse/CHA-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> deps: remove dependency on structuredClone

src/react/README.md, src/react/providers/chat-room-provider.tsx
N/A
This change adds information about memoizing the room options passed to the `ChatRoomProvider` in React.
N/A
=> docs: add react section on room option memoization

src/core/errors.ts, src/core/index.ts, src/core/messages.ts, src/core/room.ts, src/react/hooks/use-presence-listener.ts, src/react/hooks/use-typing.ts, src/react/providers/chat-room-provider.tsx, test/core/messages.integration.test.ts, test/core/room.test.ts
Fixes #350 
- Adds a promise rejection handler in ChatRoomProvider to handle unhandled rejections (due to initialization skips)
- Adds a promise rejection handler for getPreviousMessages if the room is released before initialization
- Changes the room release before initialization to use an appropriate error code
- Avoid error logging in usePresenceListener and useTyping if room is released
Open demo app, refresh many times - notice there are no errors (compare to main).
=> React unhandled rejection errors

README.md
Small improvement to the README to ensure it's obvious that you must be attached before sending room-level reactions.
=> docs: Update room-level reactions in readme for clarity.

test/core/messages.integration.test.ts, test/react/hooks/use-presence.integration.test.tsx
N/A
This change fixes the usePresence integration test. It was flaking because a leave and detach in quick succession (as the test does via unmounting) can lead to duplicate presence events as realtime will do an implicit leave for any detachments it deems still in presence.
This would lead to the presence events array having 4 events (instead of the expected 3).
The fix is to assert on seeing specific presence events we expect to see, showing that we get the desired behaviour, but without falling over because of potential race conditions.
It also fixes the messages.integration.test during the transitional period to using per-message serials.
Run the test with many repeats and observe the lack of flakeyness!
=> react/presence: fix flakey test with usePresence

test/core/messages.integration.test.ts
This reverts commit 285a088f32839b02b517a6e6486284516880fb54.
* Changes were made to support the new timeserial on a message. This is now handled in the backend.
=> Revert timeserial changes

src/core/room-options.ts, src/react/README.md
* After going through the new examples of chat in the Ably Docs, I noticed the timeout time for typing indicators seems really long for a default. It would probably confuse devs (I had to check as I thought it was set to 5 seconds) that they need to manually call `stop()`. 
* Decreased the default timeout to 5 seconds, which I think is much more reasonable.
=> chat-core: decrease timeout of the stopTyping timer

src/core/room-lifecycle-manager.ts, test/core/room-lifecycle-manager.test.ts
Resolves #398
[CHA-716]
Spec PR: https://github.com/ably/specification/pull/224
If room is in the initialized state, we can skip the detach process and skip straight to release.
N/A
[CHA-716]: https://ably.atlassian.net/browse/CHA-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> core/room: transition immediately to released if room is initialized

src/core/chat-api.ts, test/core/messages.integration.test.ts
* Pagination wouldn't correctly format subsequent data retrieved in a next() call to a default message. This is because the formatting was only called once on the first fetch of messages.
* [CHA-712]
* Refactored the pagination logic so it recursively applies formatting to any data fetch in any direction.
[CHA-712]: https://ably.atlassian.net/browse/CHA-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactor message pagination logic

demo/.env.example, demo/src/main.tsx
Small PR to make it easier to switch between local and non-local environments in the demo app. Saves us constantly commenting out code and potentially missing it in a PR.
=> Refactor Ably client initialization in the demo app

src/core/room-lifecycle-manager.ts, test/core/room-lifecycle-manager.test.ts
Closes #407
[CHA-722]
At the moment, we wind down the contributor itself. This can lead to situations where if the contributor is a shared channel, another contributor will detach the channel and thus it will never recover.
This change fixes this issue by making the comparison on the channel objects themselves.
N/A
[CHA-722]: https://ably.atlassian.net/browse/CHA-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> core/lifecycle: wind down contributors by channel during failure scenarios

src/core/connection.ts, test/core/connection.test.ts
At the moment, if a connecting status is received during a transient disconnect timer, we cancel the timer.
This isn't really ideal - as it defeats the point of a transient disconnect timeout. Equally, we suppress the error that caused the state in the first place.
This change:
- Will only cancel the transient disconnect timeout on a state that isn't connecting.
- When the transient disconnect timeout timer expires, it will pass the *current* status, but with the error from the original state change.
N/A
=> core/connection: dont cancel transient disconnect timer with connecting status

src/core/channel-manager.ts, src/core/channel.ts, src/core/messages.ts, src/core/occupancy.ts, src/core/presence.ts, src/core/room-reactions.ts, src/core/room.ts, src/core/typing.ts, test/core/channel-manager.test.ts, test/core/room.test.ts
Closes #411
[CHA-738].
This change fixes the bug described in #411 whereby channel options are overwritten by successive uses of the same channel, rather than merged together.
In doing this, we also fix the bug in relation to newly introduce spec point CHA-RC3. We were previously depending on the soft-deprecated behaviour in RTS3c which would allow you to update channel options via setOptions.
The change is achieved by adding a channel manager, whose job it is to register all the options for a given channel prior to the first channels.get() call, and call channels.get with the amalgamated options.
N/A
[CHA-738]: https://ably.atlassian.net/browse/CHA-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> core/room: add channel manager, fix bug where channel options not applied

src/core/room-lifecycle-manager.ts, test/core/room-lifecycle-manager.test.ts
Closes #406 
[CHA-723]
We weren't properly setting and unsetting the room operation in progress flag (we were only setting it to false when attaching). This change rectifies this.
Also included is the fix for async-mutex operation precedence - as the order was the wrong way around.
N/A
[CHA-723]: https://ably.atlassian.net/browse/CHA-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Room lifecycle in progress flag

test/core/messages.integration.test.ts
This PR enables the integration testing of `operation` fields in chat history. The fields inside `operation` are used for updates and deletes and give access to the clientId of user who updated or deleted, an optional user-provided `description`, and an optional user-provided `metadata`.
Part of [CHA-734](https://ably.atlassian.net/browse/CHA-734)
[CHA-734]: https://ably.atlassian.net/browse/CHA-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Test operation fields in chat history

src/core/messages.ts
We say its forwards, but it's actually backwards.
- Send 2 messages
- Call history with no options
- Convince yourself that it's correct.
=> docs: fix default history ordering annotation

README.md
Refactored the deletion aspect of chat in the README.md, so it keeps consistency with updates and provides greater clarity for its usage.
=> Refactor message docs for deletions.

README.md, src/core/chat-api.ts, src/core/index.ts, src/core/messages.ts, src/react/README.md, src/react/hooks/use-messages.ts, test/core/chat-api.test.ts, test/core/messages.integration.test.ts, test/core/messages.test.ts
As already done for Swift/Kotlin, this change renames the direction parameter of the history parameters to orderBy. Instead of using string values, we now use an enum.
The ChatApi now does a mapping to the backend format (which itself will change at a later date).
N/A
=> core: change direction to orderBy for history, use enum

demo/src/containers/Chat/Chat.tsx
* The log was attempting to dump the whole results object. This would cause a type error `Converting circular structure to JSON` and then stop the messages from being populated.
* Updated the log to correctly dump only the items in the result.
* Load up the demo with DEBUG enable, ensure the logs don't contain the type error when getting previous messages.
=> Fix: Stop logging the result object.

src/core/chat-api.ts, src/core/headers.ts, src/core/id.ts, src/core/message.ts, src/core/messages.ts, src/core/metadata.ts, src/react/helper/room-promise.ts, src/react/hooks/use-messages.ts
* Clean up of some typedoc comments
* Corrected an error in the getPreviousMessages typedoc, it stated the incorrect direction of fetched messages
* Removed an unused export from a type
=> Refactor: Clean up type docs and exports

CONTRIBUTING.md, package.json, react-native/package.json, src/react/README.md
To avoid having to change module resolution settings in Expo, this change introduces a pseudo-package `@ably/chat-react-native` which can then be used instead of `@ably/chat/react`.
Also includes README/CONTRIBUTING changes as required.
- Create an `expo` app using the default settings.
- Follow Option 2 in the React Readme,
- Try using Chat in the expo app and things should work fine.
=> react-native: add alternative installation for react native

CHANGELOG.md, CONTRIBUTING.md, README.md, UPGRADING.md, cspell.json, demo/package-lock.json, demo/package.json, package-lock.json, package.json, react-native/package.json, src/core/chat-api.ts, src/core/headers.ts, src/core/id.ts, src/core/message.ts, src/core/messages.ts, src/core/metadata.ts, src/core/version.ts, src/react/README.md, src/react/helper/room-promise.ts, src/react/hooks/use-messages.ts
[CHA-751]
This change:
- Updates the package version around the codebase
- Updates the CHANGELOG
- Updates the upcoming feature list in the README
- Adds UPGRADING.md to provide more guidance for upgrading
- Returns ably-js to tagged versions again, with the release of 2.6.0
N/A
[CHA-751]: https://ably.atlassian.net/browse/CHA-751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: 0.3.0 release

test/core/helpers.test.ts, test/react/hooks/use-presence.integration.test.tsx
Serial and created at fields were added to the test data since ably-js does not infer these from the version field.
=> Update test data with corrected action values

demo/src/App.tsx, demo/src/components/ChatBoxComponent/ChatBoxComponent.tsx, demo/src/components/ChatBoxComponent/index.ts, demo/src/components/MessageInput/MessageInput.tsx, demo/src/components/ReactionComponent/ReactionComponent.tsx, demo/src/components/ReactionComponent/index.ts, demo/src/components/TypingIndicatorPanel/TypingIndicatorPanel.tsx, demo/src/components/TypingIndicatorPanel/index.ts, demo/src/containers/Chat/Chat.tsx, demo/src/index.css
Everything was packed into this one container, so it made it confusing to understand the separation of features. This is a first pass, for now I have just moved things into their own components, but we should look at ensuring each is fully isolated and reusable.
* Please check out the demo app and play with it, everything should still work correctly.
=> Demo: Refactor demo app to reduce single component complexity.

demo/src/components/ChatBoxComponent/ChatBoxComponent.tsx, demo/src/index.css, src/core/events.ts, src/core/index.ts, src/core/message.ts, src/core/messages.ts, test/core/message.test.ts, test/core/messages.test.ts, test/react/hooks/use-messages.test.tsx
[CHA-702]
Add a new method `with()` on `Message`. `message.with(event)` is a convenience method that produces a new Message with the event applied to it. It can be used to easily apply update and delete events to a message.
Usage example
```typescript
let messages : Message[] = []; // my messages
// when receiving an update or delete event:
const idx = message.findIndex(m => m.serial == event.message.serial);
if (idx !== -1) {
messages[idx] = messages[idx].with(event);
}
```
When message reactions arrive, this method will also correctly apply reactions events to a message.
---
Another change is that the demo app now shows deleted messages with an "Edit" button. Since we have always supported what I'll call "restore by edit" it makes sense to show it in the UI, as well as to correctly …
=> Add message.with(event) method for applying message events to a Message

.github/workflows/docs.yml
Example on this PR: https://github.com/ably/ably-chat-js/pull/460
External contributors can't get a CI green at the moment because the docs upload step requires a secret in Actions that's not available on forked repos.
This change makes it so that these steps are skipped on forks, whilst still building the docs to show that they do.
This will require a process change for Ablyan reviewers on forked PRs - docs will have to be built and viewed locally, but that's a small price to pay for allowing contributors to get green CI.
=> dev: dont run docs upload step on forks

src/core/index.ts, src/core/messages.ts, src/core/occupancy.ts, src/core/presence.ts, src/core/room-reactions.ts, src/core/subscription.ts, src/core/typing.ts
Replace specialised `...SubscriptionResponse` types with the new `Subscription` interface where applicable.
- [CHA-885]
- CHADR-94
We currently have many identical interface types. This PR turns them into a single one. 
Note: not touching the ones that have `off()` as unsubscribe in this PR, will come back to those later.
Only types were changed, no functional changes.
=> Add Subscription interface

demo/src/components/ChatBoxComponent/ChatBoxComponent.tsx, src/core/index.ts, src/core/message.ts, src/core/messages.ts, src/react/hooks/use-messages.ts, test/core/message.test.ts, test/core/messages.integration.test.ts, test/react/hooks/use-messages.integration.test.tsx, test/react/hooks/use-messages.test.tsx
[CHA-865]
CHADR-092
Adds a copy method to message, to allow copies to be made with different values.
Also changes the signature of messages.update to take an updated copy of message, instead of second parameter.
N/A
[CHA-865]: https://ably.atlassian.net/browse/CHA-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add copy method to message, message update signature

test/core/messages.integration.test.ts, test/core/occupancy.integration.test.ts, test/core/presence.integration.test.ts, test/core/typing.integration.test.ts, test/core/typing.test.ts, test/helper/common.ts, test/react/hooks/use-messages.integration.test.tsx, test/react/hooks/use-presence-listener.integration.test.tsx, test/react/hooks/use-room-reactions.integration.test.tsx, test/react/hooks/use-typing.integration.test.tsx
[CHA-864]
We currently have a lot of methods that use custom promise loops, rather than using the vi.waitFor helper.
This change:
- Replaces promise loops with vi.waitFor
- Replaces duplicate methods, e.g. assertions that just check an array length after some time
Run tests!
[CHA-864]: https://ably.atlassian.net/browse/CHA-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: use vi.waitFor

src/core/connection.ts, src/core/index.ts, src/core/room-status.ts, src/core/room.ts, src/core/subscription.ts
Following on from https://github.com/ably/ably-chat-js/pull/487, adds a common interface for subscription removal that is "off" based, e.g "onStatusChange". This allows us to remove redundant, copied types.
N/A
=> refactor: common type for off-able subscriptions

src/core/channel-manager.ts, src/core/chat.ts, src/core/events.ts, src/core/occupancy.ts, src/core/reaction-parser.ts, src/core/room-status.ts, src/core/typing.ts
* Removed some redundant type checks on occupancy metrics parsing.
* _isReact is now readonly and initialized via the constructor.
* The reaction payload now does not assume the `type` field is a string, we validate this later.
* Removed an unused message action, it no longer is sent by the server, so shouldn't need to be handled.
* Minor grammar fixes and typedocs fixes
* [] Unit tests created (if applicable).
=> Refactor: Minor quality improvements

src/core/index.ts
Fixes #502
[CHA-873]
We were previously exporting OrderBy as a type and not in full, This means that users cannot do things like:
const foo = OrderBy.NewestFirst;
This change changes the export type, to make it possible to use the actual enum and not just as a type hint.
Try using a value of the `OrderBy` enum in the demo app, if it lets you, then this fix has worked!
[CHA-873]: https://ably.atlassian.net/browse/CHA-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix/messages: export OrderBy fully, not as type

README.md
Adds Node 18 to the supported versions in the README - we test against it already.
=> docs: add node18 to readme

demo/src/components/MessageInput/MessageInput.tsx, src/core/channel.ts, src/core/errors.ts, src/core/events.ts, src/core/index.ts, src/core/realtime.ts, src/core/room-options.ts, src/core/typing.ts, src/react/hooks/use-typing.ts, test/core/room.test.ts, test/core/rooms.integration.test.ts, test/core/typing.integration.test.ts, test/core/typing.test.ts, test/react/hooks/use-typing.integration.test.tsx, test/react/hooks/use-typing.test.tsx
* As part of the move to a single channel, we needed to rethink how typing works, since both typing and chat presence would have to use the same underlying realtimePresence instance. We played with the idea of a shared presence set, but this added a bit too much complexity in the SDK. 
* Instead, we decided to use heartbeats that will be published similar to the way room reactions are currently. 
* More information can be found in [CHADR-093]
* Updated the typing class to remove presence and use channel.publish() to send heartbeats
* Open the demo app and play around with the typing component.
=> Refactor: Typing with heartbeats

README.md
* Currently, chat will only work correctly if React is installed as a dependency, this is due to be fixed soon. The issue is our getting started guide doesn't mention this, so users would likely get stuck when trying to run the getting started example.
* Added `npm install react` to the guides installation section - also mentioned this will be fixed in an upcoming version.
* Corrected the room options param name, it is now exported as `AllFeaturesEnabled` instead of `RoomOptionsDefaults`.
* Create a new ts project and follow the getting started guide.
=> Docs: Update README Chat install section

src/core/chat-api.ts, src/core/message-parser.ts, src/core/message.ts, src/core/messages.ts, test/core/message.test.ts, test/react/hooks/use-messages.test.tsx
* DefaultMessage constructor was growing in size and becoming a bit unwieldy, to make it easier to read and maintain, I've refactored it to use an object-based constructor.
* [] Integration tests created (if applicable).
=> Make DefaultMessage clase use object-based constructor

src/core/connection.ts, src/core/messages.ts, src/core/occupancy.ts, src/core/presence.ts, src/core/room-reactions.ts, src/core/room-status.ts, src/core/typing.ts, src/core/utils/event-emitter.ts, test/core/connection.test.ts, test/core/messages.test.ts, test/core/occupancy.test.ts, test/core/presence.test.ts, test/core/room-reactions.test.ts, test/core/room-status.test.ts, test/core/typing.test.ts, test/react/helper/use-room-status.test.tsx
Stop extending EventEmitter so we get a cleaner public API (in JS).
Wrap all listeners into a unique reference function to make sure that subscribing the same function twice and unsubscribing one subscription will only unsubscribes that one subscription and not both.
* [CHA-856]
* [CHA-506]
[CHA-856]: https://ably.atlassian.net/browse/CHA-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHA-506]: https://ably.atlassian.net/browse/CHA-506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add unique listeners so unsubscribe() and stop extending EventEmitter

demo/.env.example, demo/src/main.tsx
N/A
- Introduced VITE_ABLY_CHAT_LOG_LEVEL in the .env.example file to allow customization of the chat client's log level.
- Saves us having to change checked-in code if we want to use a different level when running the demo.
N/A
=> demo: add log level configuration for chat client

package.json, src/core/logger.ts, src/core/messages.ts, src/core/room-status.ts, src/core/room.ts, src/react/helper/room-promise.ts, src/react/helper/use-eventual-room.ts, src/react/helper/use-room-status.ts, src/react/hooks/use-logger.ts, src/react/hooks/use-messages.ts, src/react/hooks/use-occupancy.ts, src/react/hooks/use-presence-listener.ts, src/react/hooks/use-presence.ts, src/react/hooks/use-room-reactions.ts, src/react/hooks/use-room.ts, src/react/hooks/use-typing.ts, src/react/providers/chat-room-provider.tsx, test/core/logger.test.ts, test/react/helper/use-eventual-room.test.tsx, test/react/helper/use-room-status.test.tsx, test/react/hooks/use-messages.test.tsx, test/react/hooks/use-occupancy.test.tsx, test/react/hooks/use-presence-listener.test.tsx, test/react/hooks/use-presence.test.tsx, test/react/hooks/use-room-reactions.test.tsx, test/react/hooks/use-room.test.tsx, test/react/hooks/use-typing.test.tsx
Right now, we have repetitive context parameters passed to log messages, e.g. roomId. Its easy to miss one out, and verbose.
This change introduces a `withContext` method in the Logger interface to create a logger instance with merged context.
The log calls in the context of a room now always include the roomId, and its nonce.
Also added a useRoomLogger hook to handle this in React.
Run the demo app in various contexts and observe roomIds in the logs!
=> refactor: logging contexts

demo/src/App.tsx, src/core/occupancy.ts, src/core/presence.ts, src/core/room-options.ts, src/core/room.ts, test/core/occupancy.integration.test.ts, test/core/occupancy.test.ts, test/core/presence.test.ts, test/core/room-options.test.ts, test/core/room.test.ts, test/react/hooks/use-occupancy.integration.test.tsx, test/react/providers/room-provider.test.tsx
* Renames the RoomOption for occupancy to remove the deprecated word "inband"
* Renames the RoomOption for presence events to have the same naming convention
* Adds check to presence/occupancy subscription to throw an error if trying to subscribe whilst this is turned off.
=> Occupancy events rename

README.md
in my (highly subjective) opinion this looks a bit nicer - i think it looks a bit weird that the first example of code we have in the readme suggests overriding names of functions to avoid shadowing because it makes it look like our public APIs need to be overridden even for the simplest of use cases when it isn't actually necessary
=> docs: avoid renaming functions in README example

src/core/events.ts, src/core/index.ts, src/core/typing.ts, src/react/hooks/use-typing.ts, test/core/messages.integration.test.ts, test/core/typing.integration.test.ts, test/core/typing.test.ts, test/react/hooks/use-typing.integration.test.tsx, test/react/hooks/use-typing.test.tsx
To provide better consistency with other events in Chat, the typing event payload now contains a `type` field at the root level. This also means `TypingEvents.Start` and `TypingEvents.Stop` have been replaced with `TypingEvents.SetChanged` for event emission.
=> Typing: Refactor typing events to use `SetChanged` type.

demo/src/components/MessageReactions/MessageReactionsDistinct.tsx, demo/src/components/MessageReactions/MessageReactionsMultiple.tsx, demo/src/components/MessageReactions/MessageReactionsUnique.tsx, src/core/chat-api.ts, src/core/events.ts, src/core/messages-reactions.ts, test/core/messages-reactions.integration.test.ts, test/core/messages-reactions.test.ts
- https://ably.atlassian.net/browse/CHA-980
Rename the `reaction` field to `name` in message reactions: raw reaction events, add reaction API, delete reaction API.
=> Rename reaction to name

src/core/messages-reactions.ts, test/core/messages-reactions.integration.test.ts, test/core/messages-reactions.test.ts
This happens when deleting the last reaction of a message.
=> Bugfix: empty summaries were dropped as invalid but in fact they are valid and mean there are no reactions (annotations)

.github/workflows/dev.yml
prevents annoying default behaviour where a test failure on one version of nodejs causes all other test runs to be cancelled.
=> ci: disable `fail-fast` for test jobs

demo/api/ably-token-request/index.ts, test/helper/realtime-client.ts
As of the single channel updates, capabilities can be granted to any room with just the chat qualifier - `"[chat]*":["*"]` 
* Removed the un-needed channel capability grants in the demo app and testbed.
* Start the demo app and check all features work with no 401 errors
=> feat: Update capability grants

src/core/index.ts
I found this while working on adding message reactions the ably-cli. The enum is supposed to be exported as value, not as type.
=> Export MessageReactionEvents enum as value, not type

README.md
N/A
Removed the react requirement callout in the README, as it's no-longer relevant since 0.6.0.
N/A
=> readme: remove react callout

README.md
N/A
We have the feature callouts in 3x SDK readmes, which require updating on each release. Instead
we're going to remove them and use the docs page as the source-of-truth for features.
N/A
=> readme: remove feature callout

test/core/presence.integration.test.ts
[CHA-1003](https://ably.atlassian.net/browse/CHA-1003)
Presence tests were flakey, due to a race condition with sycn messages. A room is not subscribed on attach and the presence state is not in sync, if we then enter presence (and thus attach to the underlying channel) it is possible that the first protocol message we get will be a SYNC. If this is the case, then instead of an `enter` event being emitted back to our local listener, a `present` event is emitted. 
This isn't so much of a bug, as it is expected behaviour that we should account for in the tests.
* Presence integration tests now sync their state first by calling `presence.get()`, after which, `enter` events should be correctly received. 
[CHA-101]: https://ably.atlassian.net/browse/CHA-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> Fix flakey presence tests

src/react/hooks/use-messages.ts
Non-stable refs were causing remounts each time the message state of the ChatMessage component changed. This would affect any users not providing stable refs.
* Ensure the provided reaction listeners are wrapped in `useEventListenerRef` 
=> Fix: Refactor reactions listeners to use stable refs.

demo/src/components/ReactionInput/ReactionInput.tsx, src/core/room-reactions.ts, test/core/room-reactions.integration.test.ts, test/core/room-reactions.test.ts, test/react/hooks/use-room-reactions.integration.test.tsx, test/react/hooks/use-room-reactions.test.tsx
Extracted from https://github.com/ably/ably-chat-js/pull/575
Renames `type` to `name` for sending a room reaction, for consistency with the underlying type.
=> refactor: rename room reactions params type to name

.env.test.example, .github/workflows/dev.yml, src/core/logger.ts, test/helper/chat.ts, test/helper/logger.ts, test/react/hooks/use-chat-connection.test.tsx, test/react/hooks/use-room-reactions.integration.test.tsx, test/react/providers/chat-room-provider.test.tsx
Flakey tests happen and sometimes are rare - so we want to know when a test fails, rather than have to wait ages trying to reproduce.
- Changed `consoleLogger` to be exported for use in the test cases.
- Introduced a testLogHandler to the tests which overrides the default logHander. Does nothing for passed tests, but when running on Actions it will console log everything if the test fails. This will help us debugging.
- Updated `newChatClient` and `makeTestLogger` to utilize the new logging handler.
Wait for a test to fail on actions... observe output!
=> dev: improve logging on failed tests

src/core/chat.ts, src/react/chat-client-internals.d.ts, src/react/global.d.ts, src/react/providers/chat-client-provider.tsx, test/core/chat.integration.test.ts, test/react/hooks/use-chat-client.test.tsx
* To allow us to gain insights into ui kit usage, we need a way to append the agent onto the connection.
* Added a new method `addAgentWithVersion` to the `ChatClient` class to allow for custom agent/version handling.
* ChatClientProvider now checks globalThis to see if an expected key exists for the ui kit.
=> Add support for custom agent/version handling

demo/src/components/ReactionComponent/ReactionComponent.tsx, package.json, src/core/events.ts, src/core/index.ts, src/core/room-reaction-parser.ts, src/core/room-reaction.ts, src/core/room-reactions.ts, test/core/room-reaction-parser.test.ts, test/core/room-reactions.test.ts, test/react/hooks/use-room-reactions.integration.test.tsx
CHADR-101.
[CHA-1039]
This pull request introduces a significant refactor to rename the `Reaction` interface and related types to `RoomReaction`. The changes span multiple files across the codebase, including core functionality, tests, and type exports. The refactor aims to improve clarity and consistency by aligning naming conventions with room-specific reactions.
* [`src/core/reaction.ts`](diffhunk://#diff-58e26e02e7b2b3577c57c965085b653a8bad02581a303a1ae1a383ebcfbfcb9bL7-R17): Renamed `Reaction` to `RoomReaction`, along with associated types (`ReactionHeaders`, `ReactionMetadata`) and the implementation class (`DefaultReaction` to `DefaultRoomReaction`). Updated all references accordingly. [[1]](diffhunk://#diff-58e26e02e7b2b3577c57c965085b653a8bad02581a303a1ae1a383ebcfbfcb9bL7-R17) …
=> refactor: rename Reaction to RoomReaction

demo/src/components/ChatBoxComponent/ChatBoxComponent.tsx, demo/src/components/MessageInput/MessageInput.tsx, demo/src/components/ReactionComponent/ReactionComponent.tsx, demo/src/components/ReactionInput/ReactionInput.tsx, src/react/hooks/use-messages.ts, src/react/hooks/use-room-reactions.ts, test/react/hooks/use-messages.integration.test.tsx, test/react/hooks/use-messages.test.tsx, test/react/hooks/use-room-reactions.integration.test.tsx, test/react/hooks/use-room-reactions.test.tsx
* Refactored the `send` and `update` method names in the `useMessages` hook to `sendMessage` and `updateMessage` for consistency with the other functions there now.
=> Refactor: Rename `send` and `update` names in use-messages

src/core/events.ts, src/core/typing.ts, test/core/typing.integration.test.ts, test/core/typing.test.ts, test/react/hooks/use-typing.test.tsx
[CHA-1051]
Updated TypingEventType enum values from 'Start' to 'Started' and 'Stop' to 'Stopped' to enhance clarity and maintain consistency across the SDKs (Kotlin and Swift both do this... and it reads better).
This was a mishap on the original V1 API review changes.
N/A
[CHA-1051]: https://ably.atlassian.net/browse/CHA-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: rename TypingEventType values to match Swift/Kotlin
